# This workflow will build the docker image and run the tests described in the Makefile

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v1
        with:
          username: smana
          password: ${{ secrets.dockerhub_password }}
          repository: smana/python-boilerplate
          tag_with_ref: true
          tag_with_sha: true
