# This workflow will build the docker image and run the tests described in the Makefile

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Format
        run: black -l 79 --py36 --check myapp

      - name: Complexity
        run: xenon --max-absolute=B --max-modules=B --max-average=A myapp

      - name: Lint
        run: pylint --reports=n myapp

      - name: Unit tests
        run: pytest tests

      - uses: docker/build-push-action@v1
        with:
          username: smana
          password: ${{ secrets.dockerhub_password }}
          repository: smana/python-boilerplate
          tag_with_ref: true
          tag_with_sha: true
